apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: github-event-source
      eventName: source_repo
  triggers:
    - template:
        name: argo-ci-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argo-ci-
                namespace: argo
              spec:
                serviceAccountName: argo
                entrypoint: argo-ci
#                onExit: exit-handler
                volumes:
                  - name: gcr-creds
                    secret:
                      secretName: gcr-credentials
                  - name: ssh-deploy-creds
                    secret:
                      secretName: deploy-key
                arguments:
                  parameters:
                    - name: commit_id
                      value: temp
                    - name: author
                      value: temp
                    - name: email
                      value: temp
                templates:
                  - name: argo-ci
                    steps:
                      - - name: git-checkout
                          templateRef:
                            name: ci-workflow
                            template: git-checkout-private
                          arguments:
                            parameters:
                              - name: repo
                                value: https://github.com/seongpyoHong/argo-ci-cd
                              - name: revision
                                value: master
                              - name: sshsecret
                                value: deploy-key
                              - name: sshsecretkey
                                value: ssh-privatekey
                      - - name: build-and-push
                          templateRef:
                            name: ci-workflow
                            template: build-and-push
                          arguments:
                            artifacts:
                              - name: source
                                from: ""
                            parameters:
                              - name: pathToDockerFile
                                value: "Dockerfile"
                              - name: imageUrl
                                value: "gcr.io/pinpoint/argo"
                              - name: imageTag
                                value: ""
                              - name: pathToContext
                                value: "."
                      - - name: git-new-branch
                          templateRef:
                            name: ci-workflow
                            template: git-new-branch
                          arguments:
                            parameters:
                              - name: repo
                                value: https://github.com/seongpyoHong/deploy-example
                              - name: release
                                value: ""
                      - - name: kustomize-image
                          templateRef:
                            name: ci-workflow
                            template: kustomize-image
                          arguments:
                            artifacts:
                              - name: source
                                from: ""
                            parameters:
                              - name: release
                                value: ""
                              - name: imageUrl
                                value: "gcr.io/pinpoint/argo"
                      - - name: git-commit
                          templateRef:
                            name: ci-workflow
                            template: git-commit
                          arguments:
                            artifacts:
                              - name: source
                                from: ""
                            parameters:
                              - name: release
                                value: ""
                              - name: author
                                value: ""
                              - name: email
                                value: ""
                      - - name: git-pr
                          templateRef:
                            name: ci-workflow
                            template: git-pr
                          arguments:
                            artifacts:
                              - name: source
                                from: ""

          parameters:
            - src:
                dependencyName: github
                dataKey: body.head_commit.id
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github
                dataKey: body.pusher.name
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github
                dataKey: body.pusher.email
              dest: spec.arguments.parameters.2.value