apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: github-event-source
      eventName: source_repo
  triggers:
    - template:
        name: argo-ci-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argo-ci-
                namespace: argo
              spec:
                serviceAccountName: argo
                entrypoint: argo-ci
#                onExit: exit-handler
                volumes:
                  - name: gcp-creds
                    secret:
                      secretName: argo-gcp
                  - name: ssh-deploy-creds
                    secret:
                      secretName: deploy-key
                  - name: ssh-source-creds
                    secret:
                      secretName: source-key
                arguments:
                  parameters:
                    - name: author
                      value: <author>
                    - name: email
                      value: <email>
                templates:
                  - name: argo-ci
                    steps:
                      - - name: git-checkout
                          templateRef:
                            name: ci-workflow
                            template: git-checkout-private
                          arguments:
                            parameters:
                            - name: repo
                              value: <source repository (ssh format)>
                            - name: revision
                              value: <branch for checkout>

                      - - name: build-and-push
                          templateRef:
                            name: ci-workflow
                            template: build-and-push
                          arguments:
                            artifacts:
                            - name: source
                              from: "{{steps.git-checkout.outputs.artifacts.source}}"
                            parameters:
                              - name: imageUrl
                                value: <Image Url>
                              - name: imageTag
                                value: "{{steps.git-checkout.outputs.parameters.tag}}"
                              - name: pathToContext
                                value: "."
                      - - name: git-new-branch
                          templateRef:
                            name: ci-workflow
                            template: git-new-branch
                          arguments:
                            parameters:
                              - name: repo
                                value: <deploy repository(ssh format)>
                              - name: release
                                value: "{{steps.git-checkout.outputs.parameters.tag}}"
                      - - name: kustomize-image
                          templateRef:
                            name: ci-workflow
                            template: kustomize-image
                          arguments:
                            artifacts:
                            - name: source
                              from: "{{steps.git-new-branch.outputs.artifacts.source}}"
                            parameters:
                              - name: release
                                value: "{{steps.git-checkout.outputs.parameters.tag}}"
                              - name: imageUrl
                                value: <Image Url>
                      - - name: git-commit
                          templateRef:
                            name: ci-workflow
                            template: git-commit
                          arguments:
                            artifacts:
                            - name: source
                              from: "{{steps.kustomize-image.outputs.artifacts.source}}"
                            parameters:
                              - name: release
                                value: "{{steps.git-checkout.outputs.parameters.tag}}"
                              - name: author
                                value: "{{parameters.author}}"
                              - name: email
                                value: "{{parameters.email}}"
                      - - name: git-pr
                          templateRef:
                            name: ci-workflow
                            template: git-pr
                          arguments:
                            artifacts:
                            - name: source
                              from: "{{steps.git-commit.outputs.artifacts.source}}"

          parameters:
            - src:
                dependencyName: github
                dataKey: body.pusher.name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github
                dataKey: body.pusher.email
              dest: spec.arguments.parameters.1.value