apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repository: |
    - url: <deploy repository url>
      sshPrivateKeySecret:
        name: deploy-key
        key: sshPrivateKey